# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c86d445e54ba1373901cae82ae368083ea92ebae72de33ec44b57305941c64946a934bfdc7c35b3bb5e72d0057c35673db40acac8f298bb92de4e5925270aa6a

test:
  secret_key_base: c70018e9437aef7c784a2cae8f1eaa9508cf4acdeb0e6ca0903de25dfc4626591890c501aa0ed6b54c6b9bbd6d4f53c91d48693abc020b0abe137e59f501a8e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
